import { randomUUID } from "node:crypto";
import type { ControlPlaneService } from "../domain/control-plane/control-plane.service";
import type { LifecycleService } from "../domain/lifecycle/lifecycle.service";
import type { SecurityContextService } from "../domain/security/security-context.service";
import { DemoAnalystResolver } from "../review/demo-analyst-resolver";
import type { SqliteProposalReviewRepository } from "../review/sqlite-proposal-review.repository";
import type { IdentityActionExecutor } from "./identity-action-executor";
import { ExactApprovalRequiredError,ExecutionError,ExecutionPermissionError,ExecutionStaleLifecycleError,ExecutionStaleProposalError,IdempotencyConflictError } from "./execution.errors";

export interface ExecuteActionInput{subjectId:string;expectedLifecycleVersion:number;actionId:string;proposalVersion:number;idempotencyKey:string;actorId:string;expectedActionType:"REVOKE_SESSIONS"|"REMOVE_PRIVILEGE"}
export class ActionExecutionService{
 constructor(private readonly proposals:SqliteProposalReviewRepository,private readonly control:ControlPlaneService,private readonly security:SecurityContextService,private readonly lifecycle:LifecycleService,private readonly executor:IdentityActionExecutor,private readonly analysts=new DemoAnalystResolver()){}
 async execute(input:ExecuteActionInput){const prior=this.control.getExecutionRecordByIdempotencyKey(input.idempotencyKey);if(prior){const p=prior.requestParameters;if(prior.actionId===input.actionId&&prior.proposalVersion===input.proposalVersion&&p.subjectId===input.subjectId&&p.actionType===input.expectedActionType){this.audit("EXECUTION_REPLAYED",input,prior.id);return {...prior,lifecycle:this.security.getIncident(input.subjectId).lifecycle};}throw new IdempotencyConflictError();}
  let proposal=this.proposals.latest(input.actionId);try{if(!this.analysts.resolve(input.actorId).permissions.includes("EXECUTE"))throw new ExecutionPermissionError();const context=this.security.getIncidentContext(input.subjectId);if(context.lifecycle.state!=="CONTAINING"||context.lifecycle.version!==input.expectedLifecycleVersion)throw new ExecutionStaleLifecycleError();if(!proposal||proposal.subjectId!==input.subjectId||proposal.proposalVersion!==input.proposalVersion||proposal.status!=="PROPOSED")throw new ExecutionStaleProposalError();if(proposal.actionType!==input.expectedActionType)throw new ExecutionError("WRONG_ACTION_TYPE","Execution tool does not match the proposal action type.");if(!this.proposals.findDecision(input.actionId,input.proposalVersion,"APPROVED"))throw new ExactApprovalRequiredError();this.control.validateActionProposalEvidence(proposal);if(this.control.listExecutionRecords(input.actionId).some(x=>x.proposalVersion===input.proposalVersion&&x.status==="SUCCEEDED"))throw new ExecutionError("ALREADY_EXECUTED","This proposal version already executed successfully.");
   const targets=input.expectedActionType==="REVOKE_SESSIONS"?proposal.parameters.sessionIds:proposal.parameters.privilegeIds;if(!Array.isArray(targets)||targets.some(x=>typeof x!=="string"))throw new ExecutionError("INVALID_EXECUTION_TARGET","Execution targets are invalid.");const allowed=new Set((input.expectedActionType==="REVOKE_SESSIONS"?context.sessions:context.privileges).map(x=>x.id));if(targets.some(x=>!allowed.has(x)))throw new ExecutionError("INVALID_EXECUTION_TARGET","An execution target is no longer valid.");
   const provider=this.executor.providerFor?.(input.expectedActionType)??"demo",now=new Date().toISOString(),record={id:randomUUID(),actionId:input.actionId,proposalVersion:input.proposalVersion,targetIdentifier:targets.join(","),requestParameters:{subjectId:input.subjectId,actionType:input.expectedActionType,lifecycleVersionAtStart:input.expectedLifecycleVersion,actorId:input.actorId,targets},idempotencyKey:input.idempotencyKey,status:"IN_PROGRESS" as const,startedAt:now,completedAt:null,error:null,result:null,externalAdapter:provider};this.audit("EXECUTION_REQUESTED",input,record.id);if(provider==="auth0")this.audit("EXTERNAL_EXECUTION_REQUESTED",input,record.id);this.control.saveExecutionRecord(record);this.audit("EXECUTION_STARTED",input,record.id);
   try{const result=input.expectedActionType==="REVOKE_SESSIONS"?await this.executor.revokeSessions(targets as string[]):await this.executor.removePrivileges(targets as string[]);const lifecycle=this.lifecycle.execute({caseId:input.subjectId,caseType:"INCIDENT",command:"MARK_CONTAINED",expectedVersion:input.expectedLifecycleVersion,actorId:input.actorId});const completed=this.control.updateExecutionRecord({...record,status:"SUCCEEDED",result,completedAt:new Date().toISOString()});if(provider==="auth0")this.audit("EXTERNAL_EXECUTION_SUCCEEDED",input,record.id);this.audit("EXECUTION_SUCCEEDED",input,record.id);return {...completed,lifecycle};}catch(error){const classification=typeof error==="object"&&error!==null&&"code"in error&&typeof error.code==="string"?error.code:"EXECUTION_PROVIDER_FAILURE";this.control.updateExecutionRecord({...record,status:"FAILED",completedAt:new Date().toISOString(),error:{classification,message:error instanceof Error?error.message:"Execution failed"}});if(provider==="auth0")this.audit("EXTERNAL_EXECUTION_FAILED",input,record.id,classification);this.audit("EXECUTION_FAILED",input,record.id);throw new ExecutionError("EXECUTION_PROVIDER_FAILURE","The execution provider failed.",502);}
  }catch(error){if(error instanceof ExecutionError)this.audit("EXECUTION_BLOCKED",input,null,error.message);throw error;}}
 private audit(type:string,input:ExecuteActionInput,executionId:string|null,reason?:string){this.control.appendAuditEvent({id:randomUUID(),subjectType:"INCIDENT",subjectId:input.subjectId,actorType:"WEBMCP",actorId:input.actorId,eventType:type,actionId:input.actionId,proposalVersion:input.proposalVersion,executionId,lifecycleVersion:input.expectedLifecycleVersion,source:"execution-orchestrator",metadata:{...(reason?{reason}:{})},occurredAt:new Date().toISOString()});}
}
