import Database from "better-sqlite3";
import { afterEach,beforeEach,describe,expect,it } from "vitest";
import { initializeSecuritySchema } from "../db/security-schema";
import { ControlPlaneService } from "../domain/control-plane/control-plane.service";
import { EvidenceReferenceValidator } from "../domain/control-plane/evidence-reference.validator";
import { LifecycleService } from "../domain/lifecycle/lifecycle.service";
import { SecurityContextService } from "../domain/security/security-context.service";
import { SqliteCaseRepository } from "../repositories/sqlite-case.repository";
import { SqliteControlPlaneRepository } from "../repositories/sqlite-control-plane.repository";
import { SqliteSecurityContextRepository } from "../repositories/sqlite-security-context.repository";
import { seedSecurityData } from "../seed/seed-security-data";
import { evaluateCapabilities } from "../webmcp/capability-policy";
import { CapabilityContextService } from "../webmcp/capability-context.service";
import { SqliteCapabilityContextRepository } from "../webmcp/sqlite-capability-context.repository";
import { ProposalReviewService } from "./proposal-review.service";
import { ReviewPermissionDeniedError,StaleProposalVersionError,StaleReviewLifecycleError } from "./proposal-review.errors";
import { SqliteProposalReviewRepository } from "./sqlite-proposal-review.repository";

describe("human proposal review",()=>{let db:Database.Database,service:ProposalReviewService,capabilities:CapabilityContextService;
  beforeEach(()=>{db=new Database(":memory:");initializeSecuritySchema(db);seedSecurityData(db);const securityRepo=new SqliteSecurityContextRepository(db),evidence=new EvidenceReferenceValidator(securityRepo),control=new ControlPlaneService(new SqliteControlPlaneRepository(db),evidence),lifecycle=new LifecycleService(new SqliteCaseRepository(db));
    service=new ProposalReviewService(new SqliteProposalReviewRepository(db),control,new SecurityContextService(securityRepo),evidence,lifecycle);capabilities=new CapabilityContextService(new SqliteCapabilityContextRepository(db));
    control.saveActionProposal({id:"ACT-REVIEW",proposalVersion:1,subjectType:"INCIDENT",subjectId:"INC-1001",actionType:"REVOKE_SESSIONS",parameters:{sessionIds:["SES-ASHA-SUSPICIOUS"],lifecycleVersion:3},rationale:"Review containment",evidenceRefs:["EVD-1001"],status:"PROPOSED",createdBy:"AI",createdAt:"2026-08-28T00:00:00.000Z",updatedAt:"2026-08-28T00:00:00.000Z"});
    lifecycle.execute({caseId:"INC-1001",caseType:"INCIDENT",command:"VALIDATE_CASE",expectedVersion:3,actorId:"analyst-kavya"});lifecycle.execute({caseId:"INC-1001",caseType:"INCIDENT",command:"PREPARE_RESPONSE",expectedVersion:4,actorId:"analyst-kavya"});lifecycle.execute({caseId:"INC-1001",caseType:"INCIDENT",command:"REQUEST_APPROVAL",expectedVersion:5,actorId:"analyst-kavya"});});afterEach(()=>db.close());
  const input={actionId:"ACT-REVIEW",proposalVersion:1,expectedLifecycleVersion:6,actorId:"analyst-kavya"};
  it("approves the exact version with a named transition, audit, capability, and clear read state",()=>{const result=service.approve(input);expect(result.lifecycle).toMatchObject({state:"CONTAINING",version:7});expect(result.proposal.latest).toMatchObject({proposalState:"PROPOSED",approvalState:"APPROVED",reviewState:"APPROVED"});expect(db.prepare("SELECT command FROM lifecycle_events ORDER BY occurred_at DESC LIMIT 1").get()).toEqual({command:"START_CONTAINMENT"});expect(evaluateCapabilities(capabilities.load("INCIDENT","INC-1001")).allowed.map(x=>x.toolName)).toContain("revoke_approved_sessions");expect(db.prepare("SELECT event_type FROM audit_events WHERE event_type='ACTION_APPROVED'").get()).toEqual({event_type:"ACTION_APPROVED"});});
  it("handles duplicate identical approval deterministically",()=>{const first=service.approve(input),second=service.approve(input);expect(second.duplicate).toBe(true);expect(second.decision.id).toBe(first.decision.id);expect(db.prepare("SELECT COUNT(*) count FROM approval_decisions").get()).toEqual({count:1});});
  it("rejects stale version, stale lifecycle, and missing permission",()=>{expect(()=>service.approve({...input,proposalVersion:2})).toThrow(StaleProposalVersionError);expect(()=>service.approve({...input,expectedLifecycleVersion:5})).toThrow(StaleReviewLifecycleError);expect(()=>service.approve({...input,actorId:"analyst-unknown"})).toThrow(ReviewPermissionDeniedError);});
  it("modification shows the old version as superseded and the unapproved latest version as pending",()=>{service.approve(input);const changed=service.modify({...input,expectedLifecycleVersion:7,parameters:{sessionIds:["SES-ASHA-NORMAL"]},comment:"Narrow target"});expect(changed.currentVersion).toBe(2);expect(changed.versions[0]).toMatchObject({proposalState:"SUPERSEDED",approvalState:"APPROVED",reviewState:"SUPERSEDED"});expect(changed.latest).toMatchObject({proposalVersion:2,proposalState:"PROPOSED",approvalState:"NONE",reviewState:"PENDING_REVIEW"});const context=capabilities.load("INCIDENT","INC-1001");expect(context.proposalAuthorities[0]).toMatchObject({proposalVersion:2,approvalState:"NONE"});expect(evaluateCapabilities(context).allowed.map(x=>x.toolName)).not.toContain("revoke_approved_sessions");expect(db.prepare("SELECT event_type FROM audit_events WHERE event_type='ACTION_MODIFIED'").get()).toEqual({event_type:"ACTION_MODIFIED"});});
  it("rejection displays rejected review state and never enables execution",()=>{const result=service.reject({...input,comment:"Not justified"});expect(result.proposal.latest).toMatchObject({proposalState:"PROPOSED",approvalState:"REJECTED",reviewState:"REJECTED"});const context=capabilities.load("INCIDENT","INC-1001");expect(context.approvalState).toBe("REJECTED");expect(evaluateCapabilities(context).allowed.some(x=>x.classification==="EXECUTE")).toBe(false);});
});
